package com.mahait.exceptions;

public class TryWithFinally {
	
	public static void main(String[] args) {
		try {
			System.out.println("Try");
		} 
		finally {
			System.out.println("Finally");
		}
	}

}
